Repository S1riyS/SPB-History-TG-bot, pull requests merged in 2023-12, with the labels that each got.

#4 Added inline buttons + callback factories
  data/__init__.py
  data/routes/test_route.py
  src/__main__.py
  src/callbacks/__init__.py
  src/callbacks/factories/start_route.py
  src/callbacks/start_route.py
  src/handlers/__init__.py
  src/handlers/echo.py
  src/handlers/start.py
  src/keyboards/__init__.py
  src/keyboards/all_routes.py
Labels: 🔥 enhancement

#6 Code quality improvement
  .pre-commit-config.yaml
  data/routes/test_route.py
  src/__main__.py
  src/callbacks/__init__.py
  src/callbacks/checkpoint.py
  src/callbacks/connector.py
  src/callbacks/route.py
  src/keyboards/all_routes.py
  src/keyboards/checkpoint_arrival.py
  src/keyboards/checkpoint_next.py
  src/libs/_renderable.py
  src/libs/checkpoint.py
  src/libs/checkpoints_connector.py
  src/libs/route.py
  src/libs/typing.py
Labels: 💎 code quality

#7 New content is added
  data/__init__.py
  data/routes/route1.py
  data/routes/route2.py
  data/routes/test_route.py
  src/libs/checkpoint.py
  src/libs/checkpoints_connector.py
  static/route1_0.jpg
  static/route1_1_1.jpg
  static/route1_1_2.jpg
  static/route1_2_1.jpeg
  static/route1_2_1.jpg
  static/route1_2_2.jpg
  static/route1_3_1.jpeg
  static/route1_3_2.jpg
  static/route1_4_1.jpeg
  static/route1_4_2.jpg
  static/route1_5_1.jpg
  static/route1_5_2.jpg
  static/route2_0.jpg
  static/route2_1_1.jpg
  static/route2_1_2.jpg
  static/route2_2_1.jpg
  static/route2_2_2.jpg
  static/route2_3_1.jpg
  static/route2_3_2.jpg
  static/route2_4_1.jpg
  static/route2_4_2.jpg
  static/route2_5_1.jpg
  static/route2_5_2.jpg
  static/route2_6_1.jpg
  static/route2_6_2.jpg
Labels: 🔥 enhancement

#8 CI workflow is added
  .github/workflows/ci.yml
  src/__main__.py
  src/config.py
Labels: 🔥 enhancement, 💎 code quality
